### ISSUE TITLE
About LapControl is null in build

### ISSUE THREAD

**Issue by Ghostexvan** [Ghostexvan/FinalProject#10]
- I add an IEnumerator for waiting for the player object to initiate. In Unity Editor, the execution order of scripts is from top to bottom according to their order in the hierarchy. At this point, the Player Object has been initialized and the GameplayMusicHandler can find it.
- However, after being built, their order will no longer be the same but will be in a different order. So GameplayMusicHandler cannot find the Player Object because it has not been initialized yet.
@yuurichan please close this issue after you read it.

**Comment by yuurichan** [comment]
no i will not close this issue

**Comment by yuurichan** [comment]
![download](https://github.com/Ghostexvan/FinalProject/assets/91412910/3a04547f-e1a9-451c-a4e4-2977435bc572)
